<?php

//gutenberg block field
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5d2cb5f974bf9',
	'title' => 'Video Slideshow',
	'fields' => array(
		array(
			'key' => 'field_5d2cb600dcb39',
			'label' => 'Select Slideshow',
			'name' => 'select_slideshow',
			'type' => 'post_object',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'gon_video_slideshows',
			),
			'taxonomy' => '',
			'allow_null' => 0,
			'multiple' => 0,
			'return_format' => 'id',
			'ui' => 1,
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/video-slideshow-block',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));

endif;


//home page shortcode input field
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5d1cea732a215',
	'title' => 'Video Slideshow',
	'fields' => array(
		array(
			'key' => 'field_5d1cea816b084',
			'label' => 'Video Slideshow Shortcode',
			'name' => 'video_slideshow_shortcode',
			'type' => 'text',
			'instructions' => '[gon-video-slideshow post_id="###"]',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-home.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
));


//custom post type fields

acf_add_local_field_group(array (
	'key' => 'group_599de730a5bbc',
	'title' => 'Video Slideshow',
	'fields' => array (
		array (
			'key' => 'field_59aef91956ba4',
			'label' => 'Slideshow Properties',
			'name' => 'slideshow_properties',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array (
				array (
					'key' => 'field_59aef96356ba5',
					'label' => 'Width',
					'name' => 'width',
					'type' => 'text',
					'instructions' => 'e.g. 500px or 100%',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '100%',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59aef9a956ba6',
					'label' => 'Height',
					'name' => 'height',
					'type' => 'text',
					'instructions' => 'e.g. 400px',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '50',
						'class' => '',
						'id' => '',
					),
					'default_value' => '400px',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_59a4436bd3e33',
					'label' => 'Video Overlay Content',
					'name' => 'video_overlay_content',
					'type' => 'wysiwyg',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '75',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'tabs' => 'all',
					'toolbar' => 'full',
					'media_upload' => 1,
					'delay' => 0,
				),
				array (
					'key' => 'field_59aedc773d37f',
					'label' => 'Overlay Background',
					'name' => 'overlay_background',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '25',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array (
						array (
							'key' => 'field_59aef9e356b54a7',
							'label' => 'Overlay Positioning',
							'name' => 'overlay_positioning',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'left' => 'Left',
								'right' => 'Right',
								'center' => 'Center',
								'full' => 'Full Width',
							),
							'default_value' => array (
								0 => 'left',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array (
							'key' => 'field_59aedce313b0f',
							'label' => 'Overlay Background Transparency',
							'name' => 'overlay_transparency',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'0.01' => 'Fully Transparent (0%)',
								'0.1' => '10%',
								'0.2' => '20%',
								'0.3' => '30%',
								'0.4' => '40%',
								'0.5' => '50%',
								'0.6' => '60%',
								'0.7' => '70%',
								'0.8' => '80%',
								'0.9' => '90%',
								'1' => 'Solid (100%)',
							),
							'default_value' => array (
								0 => '0.5',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array (
							'key' => 'field_59aedd1213b10',
							'label' => 'Overlay Background Shade',
							'name' => 'overlay_shade',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array (
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array (
								'Black' => 'Black',
								'White' => 'White',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
							'return_format' => 'value',
						),
					),
				)
			),
		),
		array (
			'key' => 'field_599de7363b7d6',
			'label' => 'Slides',
			'name' => 'slide',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => 'field_59asfdadfssfg3a7',
			'min' => 0,
			'max' => 3,
			'layout' => 'block',
			'button_label' => '',
			'sub_fields' => array (
				array (
					'key' => 'field_59asfdadfssfg3a7',
					'label' => 'Slide Title',
					'name' => 'slide_title',
					'type' => 'text',
					'instructions' => 'This field is not dislayed on the front end.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_57566313b10',
					'label' => 'Slide Type',
					'name' => 'slide_type',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'video' => 'Video',
						'image' => 'Image',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'horizontal',
					'return_format' => 'value',
				),
				array (
					'key' => 'field_599f2567df7e5',
					'label' => 'Video Format',
					'name' => 'video_format',
					'type' => 'radio',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_57566313b10',
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'mp4' => 'mp4',
						'ogg' => 'ogg',
						'mov' => 'mov',
						'webm' => 'webm',
						'youtube' => 'youtube',
					),
					'allow_null' => 0,
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
					'return_format' => 'value',
				),
				array (
					'key' => 'field_599de7933b7d8',
					'label' => 'Video Source',
					'name' => 'video_source',
					'type' => 'file',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_57566313b10',
								'operator' => '==',
								'value' => 'video',
							),
							array (
								'field' => 'field_599f2567df7e5',
								'operator' => '!=',
								'value' => 'youtube',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'url',
					'library' => 'all',
					'min_size' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_599f2683cbbef',
					'label' => 'Youtube Embed Source',
					'name' => 'youtube_embed_source',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_57566313b10',
								'operator' => '==',
								'value' => 'video',
							),
							array (
								'field' => 'field_599f2567df7e5',
								'operator' => '==',
								'value' => 'youtube',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array (
					'key' => 'field_599de7573b7d7',
					'label' => 'Video Screenshot',
					'name' => 'video_screenshot',
					'type' => 'image',
					'instructions' => 'Preferably the first slide of the video. This image will be used while the video is buffering, and as the slide on mobile.',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_57566313b10',
								'operator' => '==',
								'value' => 'video',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'fielfdgs7573b7d7',
					'label' => 'Image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_57566313b10',
								'operator' => '==',
								'value' => 'image',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'fielfdgs7573b7d7',
					'label' => 'Image',
					'name' => 'image',
					'type' => 'image',
					'instructions' => '',
					'required' => 1,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_57566313b10',
								'operator' => '==',
								'value' => 'image',
							),
						),
					),
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'array',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array (
					'key' => 'field_5be5f1648ebfe',
					'label' => 'Panning effect',
					'name' => 'panning_effect',
					'type' => 'true_false',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => array (
						array (
							array (
								'field' => 'field_57566313b10',
								'operator' => '==',
								'value' => 'image',
							),
						),
					),
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'message' => '',
					'default_value' => 0,
					'ui' => 0,
					'ui_on_text' => '',
					'ui_off_text' => '',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'gon_video_slideshows',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => 1,
	'description' => '',
));

endif;